# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0134_changeparameterscommand'),
    ]

    operations = [
        migrations.RunSQL([
            """
            DO $$BEGIN

            -- Delete all deltas
            UPDATE server_workflow SET last_delta_id = NULL;
            DELETE FROM server_addmodulecommand;
            DELETE FROM server_changedataversioncommand;
            DELETE FROM server_changeparametercommand;
            DELETE FROM server_changeparameterscommand;
            DELETE FROM server_changewfmodulenotescommand;
            DELETE FROM server_changewfmoduleupdatesettingscommand;
            DELETE FROM server_changeworkflowtitlecommand;
            DELETE FROM server_deletemodulecommand;
            DELETE FROM server_initworkflowcommand;
            DELETE FROM server_reordermodulescommand;
            DELETE FROM server_delta;

            -- Delete orphaned WfModules.
            -- (Previously, DeleteWorkflowCommand would point to a WfModule
            -- that's not attached to a workflow.)
            DELETE FROM server_parameterval
            WHERE wf_module_id IN (
                SELECT id FROM server_wfmodule WHERE workflow_id IS NULL
            );
            DELETE FROM server_storedobject
            WHERE wf_module_id IN (
                SELECT id FROM server_wfmodule WHERE workflow_id IS NULL
            );
            DELETE FROM server_wfmodule WHERE workflow_id IS NULL;

            -- Create new deltas. Every workflow needs at least one delta, so
            -- we can cache a render result for it. Make them
            -- InitWorkflowCommand, which is designed just for this and can't
            -- be undone.
            INSERT INTO server_delta (
                id,
                "datetime",
                workflow_id,
                polymorphic_ctype_id
            )
            SELECT
                NEXTVAL('server_delta_id_seq'),
                NOW(),
                id,
                (SELECT id FROM django_content_type WHERE model = 'initworkflowcommand')
            FROM server_workflow;

            INSERT INTO server_initworkflowcommand (delta_ptr_id)
            SELECT id FROM server_delta;

            UPDATE server_workflow
            SET last_delta_id = (
                SELECT id
                FROM server_delta
                WHERE server_delta.workflow_id = server_workflow.id
            );

            -- Wipe render cache and set new last_relevant_delta_id on
            -- WfModule.
            UPDATE server_wfmodule
            SET
                cached_render_result_error = '',
                cached_render_result_json = 'null',
                cached_render_result_workflow_id = NULL,
                cached_render_result_delta_id = NULL,
                cached_render_result_quick_fixes = '[]',
                cached_render_result_status = NULL,
                last_relevant_delta_id = (
                    SELECT id
                    FROM server_delta
                    WHERE workflow_id = server_wfmodule.workflow_id
                );

            END$$;
            """
        ])
    ]
