# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0134_changeparameterscommand'),
    ]

    operations = [
        migrations.RunSQL([
            """
            WITH
            clear_workflow_foreign_keys AS (
                UPDATE server_workflow SET last_delta_id = NULL
            ),
            -- Delete all deltas
            x01 AS (DELETE FROM server_addmodulecommand),
            x02 AS (DELETE FROM server_changedataversioncommand),
            x03 AS (DELETE FROM server_changeparametercommand),
            x04 AS (DELETE FROM server_changeparameterscommand),
            x05 AS (DELETE FROM server_changewfmodulenotescommand),
            x06 AS (DELETE FROM server_changewfmoduleupdatesettingscommand),
            x07 AS (DELETE FROM server_changeworkflowtitlecommand),
            x08 AS (DELETE FROM server_deletemodulecommand),
            x09 AS (DELETE FROM server_initworkflowcommand),
            x10 AS (DELETE FROM server_reordermodulescommand),
            x11 AS (DELETE FROM server_delta),
            wipe_deleted_params AS (
                DELETE FROM server_parameterval
                WHERE wf_module_id IN (
                    SELECT id FROM server_wfmodule
                    WHERE workflow_id IS NULL
                )
            ),
            wipe_deleted_stored_objects AS (
                DELETE FROM server_storedobject
                WHERE wf_module_id IN (
                    SELECT id FROM server_wfmodule
                    WHERE workflow_id IS NULL
                )
            ),
            wipe_deleted_wf_modules AS (
                DELETE FROM server_wfmodule WHERE workflow_id IS NULL
            ),
            wipe_wf_module_cached_render_results AS (
                UPDATE server_wfmodule
                SET
                    cached_render_result_error = '',
                    cached_render_result_json = 'null',
                    cached_render_result_workflow_id = NULL,
                    cached_render_result_delta_id = NULL,
                    cached_render_result_quick_fixes = '[]',
                    cached_render_result_status = NULL
            ),
            new_deltas AS (
                INSERT INTO server_delta (
                    id,
                    "datetime",
                    workflow_id,
                    polymorphic_ctype_id
                )
                SELECT
                    NEXTVAL('server_delta_id_seq'),
                    NOW(),
                    w.id,
                    (SELECT id FROM django_content_type WHERE model = 'initworkflowcommand')
                FROM server_workflow w
                RETURNING id, workflow_id
            ),
            fill_new_deltas AS (
                INSERT INTO server_initworkflowcommand (delta_ptr_id)
                SELECT id FROM new_deltas
            ),
            update_workflows AS (
                UPDATE server_workflow
                SET last_delta_id = (
                    SELECT id
                    FROM new_deltas
                    WHERE workflow_id = server_workflow.id
                )
            ),
            update_last_relevant_delta_ids AS (
                UPDATE server_wfmodule
                SET last_relevant_delta_id = (
                    SELECT id
                    FROM new_deltas
                    WHERE workflow_id = server_wfmodule.workflow_id
                )
            )
            SELECT 1
            """
        ])
    ]
