# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0135_wipe_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeparametercommand',
            name='delta_ptr',
        ),
        migrations.RemoveField(
            model_name='changeparametercommand',
            name='parameter_val',
        ),
        migrations.RemoveField(
            model_name='addmodulecommand',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='deletemodulecommand',
            name='applied',
        ),
        migrations.AddField(
            model_name='wfmodule',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addmodulecommand',
            name='wf_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='deletemodulecommand',
            name='wf_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.WfModule'),
        ),
        migrations.AlterField(
            model_name='wfmodule',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wf_modules', to='server.Workflow'),
        ),
        migrations.DeleteModel(
            name='ChangeParameterCommand',
        ),
    ]
