# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0137_auto_20181031_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletemodulecommand',
            name='selected_wf_module',
        ),
        migrations.RemoveField(
            model_name='wfmodule',
            name='cached_render_result_workflow_id',
        ),
    ]
