# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0141_nix_wfmodule_workflow_id_20181106_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmodule',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='server.Tab'),
        ),
    ]
