# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0142_auto_20181106_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tab',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='server.Workflow'),
        ),
    ]
